@startuml
'https://plantuml.com/class-diagram

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList



Film "1" <-- "0..m" Vorstellung
Kinosaal "1" <-- "0..m" Vorstellung
Vorstellung "1" <-- "0..m" Ticket
Sitzreihe "1" *-- "1..m" Sitzplatz
Kinosaal *-- "1..m" Sitzreihe
Warenkorb "0..1" <-- "0..m" Ticket
Sitzplatz "1" <-- Ticket

class Film {
titel: String
beschreibung: String
dauer: Int
usk: Int
genre: String
'play()
}

class Kinosaal {
name: String
}

class Vorstellung {
datum: Date
zeit: Int
status: String
'z.B. geplant, läuft, beendet
}

class Sitzreihe{
kategorie: Platzkategorie
nummer: Int
}

class Sitzplatz{
gebucht: Boolean
nummer: Int
preis: Int
}

class Ticket{
id: Int
status: String
'z.B. reserviert, bezahlt, storniert
}

class Warenkorb{
gesamtpreis: Int

}

enum Platzkategorie{
LOGEPLUS
LOGE
PARKETT
}


@enduml