@startuml
'https://plantuml.com/class-diagram

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList



Film "0..m" <-- "1" Vorstellung
Kinosaal "0..m" <-- "1" Vorstellung
Ticket --> "1" Film
Sitzreihe "1..m" <--> "1" Sitzplatz
Kinosaal --> "1..m" Sitzreihe
Ticket <-- "0..m" Warenkorb

class Film {
titel: String
beschreibung: String
dauer: Int
usk: Int
genre: String
'play()
}

class Kinosaal {
name: String
}

class Vorstellung {
datum: Date
zeit: Int

}

class Sitzreihe{
kategorie: Platzkategorie
nummer: Int
}

class Sitzplatz{
gebucht: Boolean
nummer: Int
preis: Int
}

class Ticket{
vorstellung: Vorstellung
id: Int
}

class Warenkorb{
gesamtpreis: Int

}

enum Platzkategorie{
LOGEPLUS
LOGE
PARKETT
}

'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml