//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace SeeSharper.Models.Kino
{
    
    
    /// <summary>
    /// The default implementation of the Film class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Film")]
    public partial class Film : ModelElement, IFilm, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Titel property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _titel;
        
        private static Lazy<ITypedElement> _titelAttribute = new Lazy<ITypedElement>(RetrieveTitelAttribute);
        
        /// <summary>
        /// The backing field for the Beschreibung property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _beschreibung;
        
        private static Lazy<ITypedElement> _beschreibungAttribute = new Lazy<ITypedElement>(RetrieveBeschreibungAttribute);
        
        /// <summary>
        /// The backing field for the Dauer property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _dauer;
        
        private static Lazy<ITypedElement> _dauerAttribute = new Lazy<ITypedElement>(RetrieveDauerAttribute);
        
        /// <summary>
        /// The backing field for the Fsk property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _fsk;
        
        private static Lazy<ITypedElement> _fskAttribute = new Lazy<ITypedElement>(RetrieveFskAttribute);
        
        /// <summary>
        /// The backing field for the Genre property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private string _genre;
        
        private static Lazy<ITypedElement> _genreAttribute = new Lazy<ITypedElement>(RetrieveGenreAttribute);
        
        private static Lazy<ITypedElement> _vorstellungReference = new Lazy<ITypedElement>(RetrieveVorstellungReference);
        
        /// <summary>
        /// The backing field for the Vorstellung property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private FilmVorstellungCollection _vorstellung;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Film()
        {
            this._vorstellung = new FilmVorstellungCollection(this);
            this._vorstellung.CollectionChanging += this.VorstellungCollectionChanging;
            this._vorstellung.CollectionChanged += this.VorstellungCollectionChanged;
        }
        
        /// <summary>
        /// The titel property
        /// </summary>
        [DisplayNameAttribute("titel")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("titel")]
        [XmlAttributeAttribute(true)]
        public string Titel
        {
            get
            {
                return this._titel;
            }
            set
            {
                if ((this._titel != value))
                {
                    string old = this._titel;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnTitelChanging(e);
                    this.OnPropertyChanging("Titel", e, _titelAttribute);
                    this._titel = value;
                    this.OnTitelChanged(e);
                    this.OnPropertyChanged("Titel", e, _titelAttribute);
                }
            }
        }
        
        /// <summary>
        /// The beschreibung property
        /// </summary>
        [DisplayNameAttribute("beschreibung")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("beschreibung")]
        [XmlAttributeAttribute(true)]
        public string Beschreibung
        {
            get
            {
                return this._beschreibung;
            }
            set
            {
                if ((this._beschreibung != value))
                {
                    string old = this._beschreibung;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnBeschreibungChanging(e);
                    this.OnPropertyChanging("Beschreibung", e, _beschreibungAttribute);
                    this._beschreibung = value;
                    this.OnBeschreibungChanged(e);
                    this.OnPropertyChanged("Beschreibung", e, _beschreibungAttribute);
                }
            }
        }
        
        /// <summary>
        /// The dauer property
        /// </summary>
        [DisplayNameAttribute("dauer")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("dauer")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Dauer
        {
            get
            {
                return this._dauer;
            }
            set
            {
                if ((this._dauer != value))
                {
                    Nullable<int> old = this._dauer;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnDauerChanging(e);
                    this.OnPropertyChanging("Dauer", e, _dauerAttribute);
                    this._dauer = value;
                    this.OnDauerChanged(e);
                    this.OnPropertyChanged("Dauer", e, _dauerAttribute);
                }
            }
        }
        
        /// <summary>
        /// The fsk property
        /// </summary>
        [DisplayNameAttribute("fsk")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("fsk")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Fsk
        {
            get
            {
                return this._fsk;
            }
            set
            {
                if ((this._fsk != value))
                {
                    Nullable<int> old = this._fsk;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnFskChanging(e);
                    this.OnPropertyChanging("Fsk", e, _fskAttribute);
                    this._fsk = value;
                    this.OnFskChanged(e);
                    this.OnPropertyChanged("Fsk", e, _fskAttribute);
                }
            }
        }
        
        /// <summary>
        /// The genre property
        /// </summary>
        [DisplayNameAttribute("genre")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("genre")]
        [XmlAttributeAttribute(true)]
        public string Genre
        {
            get
            {
                return this._genre;
            }
            set
            {
                if ((this._genre != value))
                {
                    string old = this._genre;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnGenreChanging(e);
                    this.OnPropertyChanging("Genre", e, _genreAttribute);
                    this._genre = value;
                    this.OnGenreChanged(e);
                    this.OnPropertyChanged("Genre", e, _genreAttribute);
                }
            }
        }
        
        /// <summary>
        /// The vorstellung property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("vorstellung")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("vorstellung")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("film")]
        [ConstantAttribute()]
        public IOrderedSetExpression<IVorstellung> Vorstellung
        {
            get
            {
                return this._vorstellung;
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new FilmReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Film")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Titel property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> TitelChanged;
        
        /// <summary>
        /// Gets fired before the Titel property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> TitelChanging;
        
        /// <summary>
        /// Gets fired when the Beschreibung property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> BeschreibungChanged;
        
        /// <summary>
        /// Gets fired before the Beschreibung property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> BeschreibungChanging;
        
        /// <summary>
        /// Gets fired when the Dauer property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> DauerChanged;
        
        /// <summary>
        /// Gets fired before the Dauer property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> DauerChanging;
        
        /// <summary>
        /// Gets fired when the Fsk property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> FskChanged;
        
        /// <summary>
        /// Gets fired before the Fsk property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> FskChanging;
        
        /// <summary>
        /// Gets fired when the Genre property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GenreChanged;
        
        /// <summary>
        /// Gets fired before the Genre property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GenreChanging;
        
        private static ITypedElement RetrieveTitelAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("titel")));
        }
        
        /// <summary>
        /// Raises the TitelChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitelChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.TitelChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the TitelChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitelChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.TitelChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveBeschreibungAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("beschreibung")));
        }
        
        /// <summary>
        /// Raises the BeschreibungChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnBeschreibungChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.BeschreibungChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the BeschreibungChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnBeschreibungChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.BeschreibungChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveDauerAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("dauer")));
        }
        
        /// <summary>
        /// Raises the DauerChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnDauerChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.DauerChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the DauerChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnDauerChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.DauerChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveFskAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("fsk")));
        }
        
        /// <summary>
        /// Raises the FskChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnFskChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.FskChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the FskChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnFskChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.FskChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveGenreAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("genre")));
        }
        
        /// <summary>
        /// Raises the GenreChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGenreChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GenreChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the GenreChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGenreChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GenreChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveVorstellungReference()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Film.ClassInstance)).Resolve("vorstellung")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Vorstellung property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void VorstellungCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Vorstellung", e, _vorstellungReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Vorstellung property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void VorstellungCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Vorstellung", e, _vorstellungReference);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "VORSTELLUNG"))
            {
                if ((index < this.Vorstellung.Count))
                {
                    return this.Vorstellung[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "TITEL"))
            {
                return this.Titel;
            }
            if ((attribute == "BESCHREIBUNG"))
            {
                return this.Beschreibung;
            }
            if ((attribute == "DAUER"))
            {
                return this.Dauer;
            }
            if ((attribute == "FSK"))
            {
                return this.Fsk;
            }
            if ((attribute == "GENRE"))
            {
                return this.Genre;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "VORSTELLUNG"))
            {
                return this._vorstellung;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "TITEL"))
            {
                this.Titel = ((string)(value));
                return;
            }
            if ((feature == "BESCHREIBUNG"))
            {
                this.Beschreibung = ((string)(value));
                return;
            }
            if ((feature == "DAUER"))
            {
                this.Dauer = ((int)(value));
                return;
            }
            if ((feature == "FSK"))
            {
                this.Fsk = ((int)(value));
                return;
            }
            if ((feature == "GENRE"))
            {
                this.Genre = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "TITEL"))
            {
                return new TitelProxy(this);
            }
            if ((attribute == "BESCHREIBUNG"))
            {
                return new BeschreibungProxy(this);
            }
            if ((attribute == "DAUER"))
            {
                return Observable.Box(new DauerProxy(this));
            }
            if ((attribute == "FSK"))
            {
                return Observable.Box(new FskProxy(this));
            }
            if ((attribute == "GENRE"))
            {
                return new GenreProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Film")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Film class
        /// </summary>
        public class FilmReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Film _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public FilmReferencedElementsCollection(Film parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Vorstellung.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.Vorstellung.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.Vorstellung.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IVorstellung vorstellungCasted = item.As<IVorstellung>();
                if ((vorstellungCasted != null))
                {
                    this._parent.Vorstellung.Add(vorstellungCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Vorstellung.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Vorstellung.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> vorstellungEnumerator = this._parent.Vorstellung.GetEnumerator();
                try
                {
                    for (
                    ; vorstellungEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = vorstellungEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    vorstellungEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IVorstellung vorstellungItem = item.As<IVorstellung>();
                if (((vorstellungItem != null) 
                            && this._parent.Vorstellung.Remove(vorstellungItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Vorstellung).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the titel property
        /// </summary>
        private sealed class TitelProxy : ModelPropertyChange<IFilm, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public TitelProxy(IFilm modelElement) : 
                    base(modelElement, "titel")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Titel;
                }
                set
                {
                    this.ModelElement.Titel = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the beschreibung property
        /// </summary>
        private sealed class BeschreibungProxy : ModelPropertyChange<IFilm, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public BeschreibungProxy(IFilm modelElement) : 
                    base(modelElement, "beschreibung")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Beschreibung;
                }
                set
                {
                    this.ModelElement.Beschreibung = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the dauer property
        /// </summary>
        private sealed class DauerProxy : ModelPropertyChange<IFilm, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public DauerProxy(IFilm modelElement) : 
                    base(modelElement, "dauer")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Dauer;
                }
                set
                {
                    this.ModelElement.Dauer = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the fsk property
        /// </summary>
        private sealed class FskProxy : ModelPropertyChange<IFilm, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public FskProxy(IFilm modelElement) : 
                    base(modelElement, "fsk")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Fsk;
                }
                set
                {
                    this.ModelElement.Fsk = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the genre property
        /// </summary>
        private sealed class GenreProxy : ModelPropertyChange<IFilm, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public GenreProxy(IFilm modelElement) : 
                    base(modelElement, "genre")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Genre;
                }
                set
                {
                    this.ModelElement.Genre = value;
                }
            }
        }
    }
}
