//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The public interface for Benutzer
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Benutzer))]
    [XmlDefaultImplementationTypeAttribute(typeof(Benutzer))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Benutzer")]
    public partial interface IBenutzer : IModelElement
    {
        
        /// <summary>
        /// The vorname property
        /// </summary>
        [DisplayNameAttribute("vorname")]
        [CategoryAttribute("Benutzer")]
        [XmlElementNameAttribute("vorname")]
        [XmlAttributeAttribute(true)]
        string Vorname
        {
            get;
            set;
        }
        
        /// <summary>
        /// The email property
        /// </summary>
        [DisplayNameAttribute("email")]
        [CategoryAttribute("Benutzer")]
        [XmlElementNameAttribute("email")]
        [XmlAttributeAttribute(true)]
        string Email
        {
            get;
            set;
        }
        
        /// <summary>
        /// The passwort property
        /// </summary>
        [DisplayNameAttribute("passwort")]
        [CategoryAttribute("Benutzer")]
        [XmlElementNameAttribute("passwort")]
        [XmlAttributeAttribute(true)]
        string Passwort
        {
            get;
            set;
        }
        
        /// <summary>
        /// The nachname property
        /// </summary>
        [DisplayNameAttribute("nachname")]
        [CategoryAttribute("Benutzer")]
        [XmlElementNameAttribute("nachname")]
        [XmlAttributeAttribute(true)]
        string Nachname
        {
            get;
            set;
        }
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Benutzer")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        Nullable <int> Id
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the Vorname property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> VornameChanged;
        
        /// <summary>
        /// Gets fired before the Vorname property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> VornameChanging;
        
        /// <summary>
        /// Gets fired when the Email property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> EmailChanged;
        
        /// <summary>
        /// Gets fired before the Email property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> EmailChanging;
        
        /// <summary>
        /// Gets fired when the Passwort property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> PasswortChanged;
        
        /// <summary>
        /// Gets fired before the Passwort property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> PasswortChanging;
        
        /// <summary>
        /// Gets fired when the Nachname property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NachnameChanged;
        
        /// <summary>
        /// Gets fired before the Nachname property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NachnameChanging;
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanging;
    }
}
