//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The public interface for Film
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Film))]
    [XmlDefaultImplementationTypeAttribute(typeof(Film))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Film")]
    public partial interface IFilm : IModelElement
    {
        
        /// <summary>
        /// The titel property
        /// </summary>
        [DisplayNameAttribute("titel")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("titel")]
        [XmlAttributeAttribute(true)]
        string Titel
        {
            get;
            set;
        }
        
        /// <summary>
        /// The beschreibung property
        /// </summary>
        [DisplayNameAttribute("beschreibung")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("beschreibung")]
        [XmlAttributeAttribute(true)]
        string Beschreibung
        {
            get;
            set;
        }
        
        /// <summary>
        /// The dauer property
        /// </summary>
        [DisplayNameAttribute("dauer")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("dauer")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Dauer
        {
            get;
            set;
        }
        
        /// <summary>
        /// The fsk property
        /// </summary>
        [DisplayNameAttribute("fsk")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("fsk")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Fsk
        {
            get;
            set;
        }
        
        /// <summary>
        /// The genre property
        /// </summary>
        [DisplayNameAttribute("genre")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("genre")]
        [XmlAttributeAttribute(true)]
        string Genre
        {
            get;
            set;
        }
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        string Id
        {
            get;
            set;
        }
        
        /// <summary>
        /// The vorstellung property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("vorstellung")]
        [CategoryAttribute("Film")]
        [XmlElementNameAttribute("vorstellung")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("film")]
        [ConstantAttribute()]
        IOrderedSetExpression<IVorstellung> Vorstellung
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the Titel property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> TitelChanged;
        
        /// <summary>
        /// Gets fired before the Titel property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> TitelChanging;
        
        /// <summary>
        /// Gets fired when the Beschreibung property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> BeschreibungChanged;
        
        /// <summary>
        /// Gets fired before the Beschreibung property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> BeschreibungChanging;
        
        /// <summary>
        /// Gets fired when the Dauer property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> DauerChanged;
        
        /// <summary>
        /// Gets fired before the Dauer property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> DauerChanging;
        
        /// <summary>
        /// Gets fired when the Fsk property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> FskChanged;
        
        /// <summary>
        /// Gets fired before the Fsk property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> FskChanging;
        
        /// <summary>
        /// Gets fired when the Genre property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> GenreChanged;
        
        /// <summary>
        /// Gets fired before the Genre property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> GenreChanging;
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanging;
    }
}
