//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities    
{
    
    
    /// <summary>
    /// The public interface for Gast
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Gast))]
    [XmlDefaultImplementationTypeAttribute(typeof(Gast))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Gast")]
    public partial interface IGast : IModelElement
    {
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Gast")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Id
        {
            get;
            set;
        }
        
        /// <summary>
        /// The warenkorb property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("warenkorb")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IWarenkorb Warenkorb
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> IdChanging;
        
        /// <summary>
        /// Gets fired before the Warenkorb property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> WarenkorbChanging;
        
        /// <summary>
        /// Gets fired when the Warenkorb property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> WarenkorbChanged;
    }
}
