//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The public interface for Kunde
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Kunde))]
    [XmlDefaultImplementationTypeAttribute(typeof(Kunde))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Kunde")]
    public partial interface IKunde : IModelElement, IBenutzer
    {
        
        /// <summary>
        /// The warenkorb property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("warenkorb")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        IWarenkorb Warenkorb
        {
            get;
            set;
        }
        
        /// <summary>
        /// The tickets property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("tickets")]
        [CategoryAttribute("Kunde")]
        [XmlElementNameAttribute("tickets")]
        [XmlAttributeAttribute(true)]
        [ConstantAttribute()]
        IOrderedSetExpression<ITicket> Tickets
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Warenkorb property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> WarenkorbChanging;
        
        /// <summary>
        /// Gets fired when the Warenkorb property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> WarenkorbChanged;
    }
}
