//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The public interface for Sitzreihe
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Sitzreihe))]
    [XmlDefaultImplementationTypeAttribute(typeof(Sitzreihe))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Sitzreihe")]
    public partial interface ISitzreihe : IModelElement
    {
        
        /// <summary>
        /// The kategorie property
        /// </summary>
        [DisplayNameAttribute("kategorie")]
        [CategoryAttribute("Sitzreihe")]
        [XmlElementNameAttribute("kategorie")]
        [XmlAttributeAttribute(true)]
        Nullable<Platzkategorie> Kategorie
        {
            get;
            set;
        }
        
        /// <summary>
        /// The nummer property
        /// </summary>
        [DisplayNameAttribute("nummer")]
        [CategoryAttribute("Sitzreihe")]
        [XmlElementNameAttribute("nummer")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Nummer
        {
            get;
            set;
        }
        
        /// <summary>
        /// The sitzplatz property
        /// </summary>
        [LowerBoundAttribute(1)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("sitzplatz")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        IOrderedSetExpression<ISitzplatz> Sitzplatz
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the Kategorie property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> KategorieChanged;
        
        /// <summary>
        /// Gets fired before the Kategorie property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> KategorieChanging;
        
        /// <summary>
        /// Gets fired when the Nummer property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NummerChanged;
        
        /// <summary>
        /// Gets fired before the Nummer property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NummerChanging;
    }
}
