//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace SeeSharper.Models.Kino
{
    
    
    /// <summary>
    /// The public interface for Sitzplatz
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Sitzplatz))]
    [XmlDefaultImplementationTypeAttribute(typeof(Sitzplatz))]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Sitzplatz")]
    public partial interface ISitzplatz : IModelElement
    {
        
        /// <summary>
        /// The gebucht property
        /// </summary>
        [DisplayNameAttribute("gebucht")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("gebucht")]
        [XmlAttributeAttribute(true)]
        Nullable<bool> Gebucht
        {
            get;
            set;
        }
        
        /// <summary>
        /// The nummer property
        /// </summary>
        [DisplayNameAttribute("nummer")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("nummer")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Nummer
        {
            get;
            set;
        }
        
        /// <summary>
        /// The preis property
        /// </summary>
        [DisplayNameAttribute("preis")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("preis")]
        [XmlAttributeAttribute(true)]
        Nullable<int> Preis
        {
            get;
            set;
        }
        
        /// <summary>
        /// The Sitzplatz property
        /// </summary>
        [DisplayNameAttribute("Sitzplatz")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("Sitzplatz")]
        [XmlAttributeAttribute(true)]
        ITicket Sitzplatz_
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired when the Gebucht property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> GebuchtChanged;
        
        /// <summary>
        /// Gets fired before the Gebucht property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> GebuchtChanging;
        
        /// <summary>
        /// Gets fired when the Nummer property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NummerChanged;
        
        /// <summary>
        /// Gets fired before the Nummer property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> NummerChanging;
        
        /// <summary>
        /// Gets fired when the Preis property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> PreisChanged;
        
        /// <summary>
        /// Gets fired before the Preis property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> PreisChanging;
        
        /// <summary>
        /// Gets fired before the Sitzplatz_ property changes its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> Sitzplatz_Changing;
        
        /// <summary>
        /// Gets fired when the Sitzplatz_ property changed its value
        /// </summary>
        event EventHandler<ValueChangedEventArgs> Sitzplatz_Changed;
    }
}
