//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace SeeSharper.Models.Kino
{
    
    
    /// <summary>
    /// The default implementation of the Kunde class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Kunde")]
    [DebuggerDisplayAttribute("Kunde {Name}")]
    public partial class Kunde : Benutzer, IKunde, IModelElement
    {
        
        private static Lazy<ITypedElement> _warenkorbReference = new Lazy<ITypedElement>(RetrieveWarenkorbReference);
        
        /// <summary>
        /// The backing field for the Warenkorb property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private IWarenkorb _warenkorb;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The warenkorb property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("warenkorb")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        public IWarenkorb Warenkorb
        {
            get
            {
                return this._warenkorb;
            }
            set
            {
                if ((this._warenkorb != value))
                {
                    IWarenkorb old = this._warenkorb;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnWarenkorbChanging(e);
                    this.OnPropertyChanging("Warenkorb", e, _warenkorbReference);
                    this._warenkorb = value;
                    if ((old != null))
                    {
                        if ((old.Parent == this))
                        {
                            old.Parent = null;
                        }
                        old.ParentChanged -= this.OnResetWarenkorb;
                    }
                    if ((value != null))
                    {
                        value.Parent = this;
                        value.ParentChanged += this.OnResetWarenkorb;
                    }
                    this.OnWarenkorbChanged(e);
                    this.OnPropertyChanged("Warenkorb", e, _warenkorbReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new KundeChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new KundeReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Kunde")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Warenkorb property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> WarenkorbChanging;
        
        /// <summary>
        /// Gets fired when the Warenkorb property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> WarenkorbChanged;
        
        private static ITypedElement RetrieveWarenkorbReference()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Kunde.ClassInstance)).Resolve("warenkorb")));
        }
        
        /// <summary>
        /// Raises the WarenkorbChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWarenkorbChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.WarenkorbChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the WarenkorbChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWarenkorbChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.WarenkorbChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Warenkorb property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetWarenkorb(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Warenkorb))
            {
                this.Warenkorb = null;
            }
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            if ((element == this.Warenkorb))
            {
                return ModelHelper.CreatePath("warenkorb");
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "WARENKORB"))
            {
                return this.Warenkorb;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "WARENKORB"))
            {
                this.Warenkorb = ((IWarenkorb)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "WARENKORB"))
            {
                return new WarenkorbProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Kunde")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Kunde class
        /// </summary>
        public class KundeChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Kunde _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public KundeChildrenCollection(Kunde parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Warenkorb != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.WarenkorbChanged += this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.WarenkorbChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Warenkorb == null))
                {
                    IWarenkorb warenkorbCasted = item.As<IWarenkorb>();
                    if ((warenkorbCasted != null))
                    {
                        this._parent.Warenkorb = warenkorbCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Warenkorb = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Warenkorb))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Warenkorb != null))
                {
                    array[arrayIndex] = this._parent.Warenkorb;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Warenkorb == item))
                {
                    this._parent.Warenkorb = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Warenkorb).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Kunde class
        /// </summary>
        public class KundeReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Kunde _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public KundeReferencedElementsCollection(Kunde parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Warenkorb != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.WarenkorbChanged += this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.WarenkorbChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Warenkorb == null))
                {
                    IWarenkorb warenkorbCasted = item.As<IWarenkorb>();
                    if ((warenkorbCasted != null))
                    {
                        this._parent.Warenkorb = warenkorbCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Warenkorb = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Warenkorb))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Warenkorb != null))
                {
                    array[arrayIndex] = this._parent.Warenkorb;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Warenkorb == item))
                {
                    this._parent.Warenkorb = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Warenkorb).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the warenkorb property
        /// </summary>
        private sealed class WarenkorbProxy : ModelPropertyChange<IKunde, IWarenkorb>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public WarenkorbProxy(IKunde modelElement) : 
                    base(modelElement, "warenkorb")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IWarenkorb Value
            {
                get
                {
                    return this.ModelElement.Warenkorb;
                }
                set
                {
                    this.ModelElement.Warenkorb = value;
                }
            }
        }
    }
}
