//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The default implementation of the Sitzplatz class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Sitzplatz")]
    public partial class Sitzplatz : ModelElement, ISitzplatz, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Gebucht property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<bool> _gebucht;
        
        private static Lazy<ITypedElement> _gebuchtAttribute = new Lazy<ITypedElement>(RetrieveGebuchtAttribute);
        
        /// <summary>
        /// The backing field for the Nummer property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _nummer;
        
        private static Lazy<ITypedElement> _nummerAttribute = new Lazy<ITypedElement>(RetrieveNummerAttribute);
        
        /// <summary>
        /// The backing field for the Preis property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _preis;
        
        private static Lazy<ITypedElement> _preisAttribute = new Lazy<ITypedElement>(RetrievePreisAttribute);
        
        /// <summary>
        /// The backing field for the Id property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _id;
        
        private static Lazy<ITypedElement> _idAttribute = new Lazy<ITypedElement>(RetrieveIdAttribute);
        
        private static Lazy<ITypedElement> _sitzplatzReference = new Lazy<ITypedElement>(RetrieveSitzplatzReference);
        
        /// <summary>
        /// The backing field for the Sitzplatz_ property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ITicket _sitzplatz_;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The gebucht property
        /// </summary>
        [DisplayNameAttribute("gebucht")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("gebucht")]
        [XmlAttributeAttribute(true)]
        public Nullable<bool> Gebucht
        {
            get
            {
                return this._gebucht;
            }
            set
            {
                if ((this._gebucht != value))
                {
                    Nullable<bool> old = this._gebucht;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnGebuchtChanging(e);
                    this.OnPropertyChanging("Gebucht", e, _gebuchtAttribute);
                    this._gebucht = value;
                    this.OnGebuchtChanged(e);
                    this.OnPropertyChanged("Gebucht", e, _gebuchtAttribute);
                }
            }
        }
        
        /// <summary>
        /// The nummer property
        /// </summary>
        [DisplayNameAttribute("nummer")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("nummer")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Nummer
        {
            get
            {
                return this._nummer;
            }
            set
            {
                if ((this._nummer != value))
                {
                    Nullable<int> old = this._nummer;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnNummerChanging(e);
                    this.OnPropertyChanging("Nummer", e, _nummerAttribute);
                    this._nummer = value;
                    this.OnNummerChanged(e);
                    this.OnPropertyChanged("Nummer", e, _nummerAttribute);
                }
            }
        }
        
        /// <summary>
        /// The preis property
        /// </summary>
        [DisplayNameAttribute("preis")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("preis")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Preis
        {
            get
            {
                return this._preis;
            }
            set
            {
                if ((this._preis != value))
                {
                    Nullable<int> old = this._preis;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPreisChanging(e);
                    this.OnPropertyChanging("Preis", e, _preisAttribute);
                    this._preis = value;
                    this.OnPreisChanged(e);
                    this.OnPropertyChanged("Preis", e, _preisAttribute);
                }
            }
        }
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    Nullable<int> old = this._id;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnIdChanging(e);
                    this.OnPropertyChanging("Id", e, _idAttribute);
                    this._id = value;
                    this.OnIdChanged(e);
                    this.OnPropertyChanged("Id", e, _idAttribute);
                }
            }
        }
        
        /// <summary>
        /// The Sitzplatz property
        /// </summary>
        [DisplayNameAttribute("Sitzplatz")]
        [CategoryAttribute("Sitzplatz")]
        [XmlElementNameAttribute("Sitzplatz")]
        [XmlAttributeAttribute(true)]
        public ITicket Sitzplatz_
        {
            get
            {
                return this._sitzplatz_;
            }
            set
            {
                if ((this._sitzplatz_ != value))
                {
                    ITicket old = this._sitzplatz_;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnSitzplatz_Changing(e);
                    this.OnPropertyChanging("Sitzplatz_", e, _sitzplatzReference);
                    this._sitzplatz_ = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetSitzplatz_;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetSitzplatz_;
                    }
                    this.OnSitzplatz_Changed(e);
                    this.OnPropertyChanged("Sitzplatz_", e, _sitzplatzReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new SitzplatzReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Sitzplatz")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Gebucht property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GebuchtChanged;
        
        /// <summary>
        /// Gets fired before the Gebucht property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GebuchtChanging;
        
        /// <summary>
        /// Gets fired when the Nummer property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> NummerChanged;
        
        /// <summary>
        /// Gets fired before the Nummer property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> NummerChanging;
        
        /// <summary>
        /// Gets fired when the Preis property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> PreisChanged;
        
        /// <summary>
        /// Gets fired before the Preis property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> PreisChanging;
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanging;
        
        /// <summary>
        /// Gets fired before the Sitzplatz_ property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> Sitzplatz_Changing;
        
        /// <summary>
        /// Gets fired when the Sitzplatz_ property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> Sitzplatz_Changed;
        
        private static ITypedElement RetrieveGebuchtAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzplatz.ClassInstance)).Resolve("gebucht")));
        }
        
        /// <summary>
        /// Raises the GebuchtChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGebuchtChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GebuchtChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the GebuchtChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGebuchtChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GebuchtChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveNummerAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzplatz.ClassInstance)).Resolve("nummer")));
        }
        
        /// <summary>
        /// Raises the NummerChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNummerChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.NummerChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the NummerChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNummerChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.NummerChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrievePreisAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzplatz.ClassInstance)).Resolve("preis")));
        }
        
        /// <summary>
        /// Raises the PreisChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPreisChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.PreisChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the PreisChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPreisChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.PreisChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveIdAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzplatz.ClassInstance)).Resolve("id")));
        }
        
        /// <summary>
        /// Raises the IdChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the IdChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveSitzplatzReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzplatz.ClassInstance)).Resolve("Sitzplatz")));
        }
        
        /// <summary>
        /// Raises the Sitzplatz_Changing event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSitzplatz_Changing(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.Sitzplatz_Changing;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the Sitzplatz_Changed event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSitzplatz_Changed(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.Sitzplatz_Changed;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Sitzplatz_ property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetSitzplatz_(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Sitzplatz_))
            {
                this.Sitzplatz_ = null;
            }
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "SITZPLATZ"))
            {
                return this.Sitzplatz_;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "GEBUCHT"))
            {
                return this.Gebucht;
            }
            if ((attribute == "NUMMER"))
            {
                return this.Nummer;
            }
            if ((attribute == "PREIS"))
            {
                return this.Preis;
            }
            if ((attribute == "ID"))
            {
                return this.Id;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "SITZPLATZ"))
            {
                this.Sitzplatz_ = ((ITicket)(value));
                return;
            }
            if ((feature == "GEBUCHT"))
            {
                this.Gebucht = ((bool)(value));
                return;
            }
            if ((feature == "NUMMER"))
            {
                this.Nummer = ((int)(value));
                return;
            }
            if ((feature == "PREIS"))
            {
                this.Preis = ((int)(value));
                return;
            }
            if ((feature == "ID"))
            {
                this.Id = ((int)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "GEBUCHT"))
            {
                return Observable.Box(new GebuchtProxy(this));
            }
            if ((attribute == "NUMMER"))
            {
                return Observable.Box(new NummerProxy(this));
            }
            if ((attribute == "PREIS"))
            {
                return Observable.Box(new PreisProxy(this));
            }
            if ((attribute == "ID"))
            {
                return Observable.Box(new IdProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "SITZPLATZ_"))
            {
                return new SitzplatzProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Sitzplatz")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Sitzplatz class
        /// </summary>
        public class SitzplatzReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Sitzplatz _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public SitzplatzReferencedElementsCollection(Sitzplatz parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Sitzplatz_ != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.Sitzplatz_Changed += this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.Sitzplatz_Changed -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Sitzplatz_ == null))
                {
                    ITicket sitzplatzCasted = item.As<ITicket>();
                    if ((sitzplatzCasted != null))
                    {
                        this._parent.Sitzplatz_ = sitzplatzCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Sitzplatz_ = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Sitzplatz_))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Sitzplatz_ != null))
                {
                    array[arrayIndex] = this._parent.Sitzplatz_;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Sitzplatz_ == item))
                {
                    this._parent.Sitzplatz_ = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Sitzplatz_).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the gebucht property
        /// </summary>
        private sealed class GebuchtProxy : ModelPropertyChange<ISitzplatz, Nullable<bool>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public GebuchtProxy(ISitzplatz modelElement) : 
                    base(modelElement, "gebucht")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<bool> Value
            {
                get
                {
                    return this.ModelElement.Gebucht;
                }
                set
                {
                    this.ModelElement.Gebucht = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the nummer property
        /// </summary>
        private sealed class NummerProxy : ModelPropertyChange<ISitzplatz, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NummerProxy(ISitzplatz modelElement) : 
                    base(modelElement, "nummer")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Nummer;
                }
                set
                {
                    this.ModelElement.Nummer = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the preis property
        /// </summary>
        private sealed class PreisProxy : ModelPropertyChange<ISitzplatz, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public PreisProxy(ISitzplatz modelElement) : 
                    base(modelElement, "preis")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Preis;
                }
                set
                {
                    this.ModelElement.Preis = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the id property
        /// </summary>
        private sealed class IdProxy : ModelPropertyChange<ISitzplatz, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public IdProxy(ISitzplatz modelElement) : 
                    base(modelElement, "id")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Id;
                }
                set
                {
                    this.ModelElement.Id = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Sitzplatz property
        /// </summary>
        private sealed class SitzplatzProxy : ModelPropertyChange<ISitzplatz, ITicket>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public SitzplatzProxy(ISitzplatz modelElement) : 
                    base(modelElement, "Sitzplatz")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override ITicket Value
            {
                get
                {
                    return this.ModelElement.Sitzplatz_;
                }
                set
                {
                    this.ModelElement.Sitzplatz_ = value;
                }
            }
        }
    }
}
