//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The default implementation of the Sitzreihe class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Sitzreihe")]
    public partial class Sitzreihe : ModelElement, ISitzreihe, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Kategorie property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<Platzkategorie> _kategorie;
        
        private static Lazy<ITypedElement> _kategorieAttribute = new Lazy<ITypedElement>(RetrieveKategorieAttribute);
        
        /// <summary>
        /// The backing field for the Nummer property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _nummer;
        
        private static Lazy<ITypedElement> _nummerAttribute = new Lazy<ITypedElement>(RetrieveNummerAttribute);
        
        /// <summary>
        /// The backing field for the Id property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _id;
        
        private static Lazy<ITypedElement> _idAttribute = new Lazy<ITypedElement>(RetrieveIdAttribute);
        
        private static Lazy<ITypedElement> _sitzplatzReference = new Lazy<ITypedElement>(RetrieveSitzplatzReference);
        
        /// <summary>
        /// The backing field for the Sitzplatz property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ObservableCompositionOrderedSet<ISitzplatz> _sitzplatz;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Sitzreihe()
        {
            this._sitzplatz = new ObservableCompositionOrderedSet<ISitzplatz>(this);
            this._sitzplatz.CollectionChanging += this.SitzplatzCollectionChanging;
            this._sitzplatz.CollectionChanged += this.SitzplatzCollectionChanged;
        }
        
        /// <summary>
        /// The kategorie property
        /// </summary>
        [DisplayNameAttribute("kategorie")]
        [CategoryAttribute("Sitzreihe")]
        [XmlElementNameAttribute("kategorie")]
        [XmlAttributeAttribute(true)]
        public Nullable<Platzkategorie> Kategorie
        {
            get
            {
                return this._kategorie;
            }
            set
            {
                if ((this._kategorie != value))
                {
                    Nullable<Platzkategorie> old = this._kategorie;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnKategorieChanging(e);
                    this.OnPropertyChanging("Kategorie", e, _kategorieAttribute);
                    this._kategorie = value;
                    this.OnKategorieChanged(e);
                    this.OnPropertyChanged("Kategorie", e, _kategorieAttribute);
                }
            }
        }
        
        /// <summary>
        /// The nummer property
        /// </summary>
        [DisplayNameAttribute("nummer")]
        [CategoryAttribute("Sitzreihe")]
        [XmlElementNameAttribute("nummer")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Nummer
        {
            get
            {
                return this._nummer;
            }
            set
            {
                if ((this._nummer != value))
                {
                    Nullable<int> old = this._nummer;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnNummerChanging(e);
                    this.OnPropertyChanging("Nummer", e, _nummerAttribute);
                    this._nummer = value;
                    this.OnNummerChanged(e);
                    this.OnPropertyChanged("Nummer", e, _nummerAttribute);
                }
            }
        }
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Sitzreihe")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    Nullable<int> old = this._id;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnIdChanging(e);
                    this.OnPropertyChanging("Id", e, _idAttribute);
                    this._id = value;
                    this.OnIdChanged(e);
                    this.OnPropertyChanged("Id", e, _idAttribute);
                }
            }
        }
        
        /// <summary>
        /// The sitzplatz property
        /// </summary>
        [LowerBoundAttribute(1)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("sitzplatz")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<ISitzplatz> Sitzplatz
        {
            get
            {
                return this._sitzplatz;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new SitzreiheChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new SitzreiheReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Sitzreihe")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Kategorie property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> KategorieChanged;
        
        /// <summary>
        /// Gets fired before the Kategorie property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> KategorieChanging;
        
        /// <summary>
        /// Gets fired when the Nummer property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> NummerChanged;
        
        /// <summary>
        /// Gets fired before the Nummer property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> NummerChanging;
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanging;
        
        private static ITypedElement RetrieveKategorieAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzreihe.ClassInstance)).Resolve("kategorie")));
        }
        
        /// <summary>
        /// Raises the KategorieChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnKategorieChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.KategorieChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the KategorieChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnKategorieChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.KategorieChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveNummerAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzreihe.ClassInstance)).Resolve("nummer")));
        }
        
        /// <summary>
        /// Raises the NummerChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNummerChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.NummerChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the NummerChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNummerChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.NummerChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveIdAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzreihe.ClassInstance)).Resolve("id")));
        }
        
        /// <summary>
        /// Raises the IdChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the IdChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveSitzplatzReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Sitzreihe.ClassInstance)).Resolve("sitzplatz")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Sitzplatz property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void SitzplatzCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Sitzplatz", e, _sitzplatzReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Sitzplatz property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void SitzplatzCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Sitzplatz", e, _sitzplatzReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int sitzplatzIndex = ModelHelper.IndexOfReference(this.Sitzplatz, element);
            if ((sitzplatzIndex != -1))
            {
                return ModelHelper.CreatePath("sitzplatz", sitzplatzIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "SITZPLATZ"))
            {
                if ((index < this.Sitzplatz.Count))
                {
                    return this.Sitzplatz[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "KATEGORIE"))
            {
                return this.Kategorie;
            }
            if ((attribute == "NUMMER"))
            {
                return this.Nummer;
            }
            if ((attribute == "ID"))
            {
                return this.Id;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "SITZPLATZ"))
            {
                return this._sitzplatz;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "KATEGORIE"))
            {
                this.Kategorie = ((Platzkategorie)(value));
                return;
            }
            if ((feature == "NUMMER"))
            {
                this.Nummer = ((int)(value));
                return;
            }
            if ((feature == "ID"))
            {
                this.Id = ((int)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "KATEGORIE"))
            {
                return Observable.Box(new KategorieProxy(this));
            }
            if ((attribute == "NUMMER"))
            {
                return Observable.Box(new NummerProxy(this));
            }
            if ((attribute == "ID"))
            {
                return Observable.Box(new IdProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._sitzplatz))
            {
                return "sitzplatz";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Sitzreihe")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Sitzreihe class
        /// </summary>
        public class SitzreiheChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Sitzreihe _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public SitzreiheChildrenCollection(Sitzreihe parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Sitzplatz.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.Sitzplatz.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.Sitzplatz.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                ISitzplatz sitzplatzCasted = item.As<ISitzplatz>();
                if ((sitzplatzCasted != null))
                {
                    this._parent.Sitzplatz.Add(sitzplatzCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Sitzplatz.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Sitzplatz.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> sitzplatzEnumerator = this._parent.Sitzplatz.GetEnumerator();
                try
                {
                    for (
                    ; sitzplatzEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = sitzplatzEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    sitzplatzEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                ISitzplatz sitzplatzItem = item.As<ISitzplatz>();
                if (((sitzplatzItem != null) 
                            && this._parent.Sitzplatz.Remove(sitzplatzItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Sitzplatz).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Sitzreihe class
        /// </summary>
        public class SitzreiheReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Sitzreihe _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public SitzreiheReferencedElementsCollection(Sitzreihe parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Sitzplatz.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.Sitzplatz.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.Sitzplatz.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                ISitzplatz sitzplatzCasted = item.As<ISitzplatz>();
                if ((sitzplatzCasted != null))
                {
                    this._parent.Sitzplatz.Add(sitzplatzCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Sitzplatz.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Sitzplatz.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> sitzplatzEnumerator = this._parent.Sitzplatz.GetEnumerator();
                try
                {
                    for (
                    ; sitzplatzEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = sitzplatzEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    sitzplatzEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                ISitzplatz sitzplatzItem = item.As<ISitzplatz>();
                if (((sitzplatzItem != null) 
                            && this._parent.Sitzplatz.Remove(sitzplatzItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Sitzplatz).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the kategorie property
        /// </summary>
        private sealed class KategorieProxy : ModelPropertyChange<ISitzreihe, Nullable<Platzkategorie>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public KategorieProxy(ISitzreihe modelElement) : 
                    base(modelElement, "kategorie")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<Platzkategorie> Value
            {
                get
                {
                    return this.ModelElement.Kategorie;
                }
                set
                {
                    this.ModelElement.Kategorie = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the nummer property
        /// </summary>
        private sealed class NummerProxy : ModelPropertyChange<ISitzreihe, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public NummerProxy(ISitzreihe modelElement) : 
                    base(modelElement, "nummer")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Nummer;
                }
                set
                {
                    this.ModelElement.Nummer = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the id property
        /// </summary>
        private sealed class IdProxy : ModelPropertyChange<ISitzreihe, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public IdProxy(ISitzreihe modelElement) : 
                    base(modelElement, "id")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Id;
                }
                set
                {
                    this.ModelElement.Id = value;
                }
            }
        }
    }
}
