//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace KinoAppCore.Entities
{
    
    
    /// <summary>
    /// The default implementation of the Ticket class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Ticket")]
    public partial class Ticket : ModelElement, ITicket, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Id property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _id;
        
        private static Lazy<ITypedElement> _idAttribute = new Lazy<ITypedElement>(RetrieveIdAttribute);
        
        /// <summary>
        /// The backing field for the Status property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<Ticketstatus> _status;
        
        private static Lazy<ITypedElement> _statusAttribute = new Lazy<ITypedElement>(RetrieveStatusAttribute);
        
        private static Lazy<ITypedElement> _warenkorbReference = new Lazy<ITypedElement>(RetrieveWarenkorbReference);
        
        /// <summary>
        /// The backing field for the Warenkorb property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private IWarenkorb _warenkorb;
        
        private static Lazy<ITypedElement> _vorstellungReference = new Lazy<ITypedElement>(RetrieveVorstellungReference);
        
        /// <summary>
        /// The backing field for the Vorstellung property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private IVorstellung _vorstellung;
        
        private static Lazy<ITypedElement> _sitzplatzReference = new Lazy<ITypedElement>(RetrieveSitzplatzReference);
        
        /// <summary>
        /// The backing field for the Sitzplatz property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private ISitzplatz _sitzplatz;
        
        private static Lazy<ITypedElement> _kundeReference = new Lazy<ITypedElement>(RetrieveKundeReference);
        
        /// <summary>
        /// The backing field for the Kunde property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private IKunde _kunde;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The id property
        /// </summary>
        [DisplayNameAttribute("id")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("id")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    Nullable<int> old = this._id;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnIdChanging(e);
                    this.OnPropertyChanging("Id", e, _idAttribute);
                    this._id = value;
                    this.OnIdChanged(e);
                    this.OnPropertyChanged("Id", e, _idAttribute);
                }
            }
        }
        
        /// <summary>
        /// The status property
        /// </summary>
        [DisplayNameAttribute("status")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("status")]
        [XmlAttributeAttribute(true)]
        public Nullable<Ticketstatus> Status
        {
            get
            {
                return this._status;
            }
            set
            {
                if ((this._status != value))
                {
                    Nullable<Ticketstatus> old = this._status;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnStatusChanging(e);
                    this.OnPropertyChanging("Status", e, _statusAttribute);
                    this._status = value;
                    this.OnStatusChanged(e);
                    this.OnPropertyChanged("Status", e, _statusAttribute);
                }
            }
        }
        
        /// <summary>
        /// The warenkorb property
        /// </summary>
        [DisplayNameAttribute("warenkorb")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("warenkorb")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("ticket")]
        public IWarenkorb Warenkorb
        {
            get
            {
                return this._warenkorb;
            }
            set
            {
                if ((this._warenkorb != value))
                {
                    IWarenkorb old = this._warenkorb;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnWarenkorbChanging(e);
                    this.OnPropertyChanging("Warenkorb", e, _warenkorbReference);
                    this._warenkorb = value;
                    if ((old != null))
                    {
                        old.Ticket.Remove(this);
                        old.Deleted -= this.OnResetWarenkorb;
                    }
                    if ((value != null))
                    {
                        value.Ticket.Add(this);
                        value.Deleted += this.OnResetWarenkorb;
                    }
                    this.OnWarenkorbChanged(e);
                    this.OnPropertyChanged("Warenkorb", e, _warenkorbReference);
                }
            }
        }
        
        /// <summary>
        /// The vorstellung property
        /// </summary>
        [DisplayNameAttribute("vorstellung")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("vorstellung")]
        [XmlAttributeAttribute(true)]
        public IVorstellung Vorstellung
        {
            get
            {
                return this._vorstellung;
            }
            set
            {
                if ((this._vorstellung != value))
                {
                    IVorstellung old = this._vorstellung;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnVorstellungChanging(e);
                    this.OnPropertyChanging("Vorstellung", e, _vorstellungReference);
                    this._vorstellung = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetVorstellung;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetVorstellung;
                    }
                    this.OnVorstellungChanged(e);
                    this.OnPropertyChanged("Vorstellung", e, _vorstellungReference);
                }
            }
        }
        
        /// <summary>
        /// The sitzplatz property
        /// </summary>
        [DisplayNameAttribute("sitzplatz")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("sitzplatz")]
        [XmlAttributeAttribute(true)]
        public ISitzplatz Sitzplatz
        {
            get
            {
                return this._sitzplatz;
            }
            set
            {
                if ((this._sitzplatz != value))
                {
                    ISitzplatz old = this._sitzplatz;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnSitzplatzChanging(e);
                    this.OnPropertyChanging("Sitzplatz", e, _sitzplatzReference);
                    this._sitzplatz = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetSitzplatz;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetSitzplatz;
                    }
                    this.OnSitzplatzChanged(e);
                    this.OnPropertyChanged("Sitzplatz", e, _sitzplatzReference);
                }
            }
        }
        
        /// <summary>
        /// The kunde property
        /// </summary>
        [DisplayNameAttribute("kunde")]
        [CategoryAttribute("Ticket")]
        [XmlElementNameAttribute("kunde")]
        [XmlAttributeAttribute(true)]
        public IKunde Kunde
        {
            get
            {
                return this._kunde;
            }
            set
            {
                if ((this._kunde != value))
                {
                    IKunde old = this._kunde;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnKundeChanging(e);
                    this.OnPropertyChanging("Kunde", e, _kundeReference);
                    this._kunde = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetKunde;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetKunde;
                    }
                    this.OnKundeChanged(e);
                    this.OnPropertyChanged("Kunde", e, _kundeReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new TicketReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Ticket")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> IdChanging;
        
        /// <summary>
        /// Gets fired when the Status property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> StatusChanged;
        
        /// <summary>
        /// Gets fired before the Status property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> StatusChanging;
        
        /// <summary>
        /// Gets fired before the Warenkorb property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> WarenkorbChanging;
        
        /// <summary>
        /// Gets fired when the Warenkorb property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> WarenkorbChanged;
        
        /// <summary>
        /// Gets fired before the Vorstellung property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> VorstellungChanging;
        
        /// <summary>
        /// Gets fired when the Vorstellung property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> VorstellungChanged;
        
        /// <summary>
        /// Gets fired before the Sitzplatz property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> SitzplatzChanging;
        
        /// <summary>
        /// Gets fired when the Sitzplatz property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> SitzplatzChanged;
        
        /// <summary>
        /// Gets fired before the Kunde property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> KundeChanging;
        
        /// <summary>
        /// Gets fired when the Kunde property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> KundeChanged;
        
        private static ITypedElement RetrieveIdAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("id")));
        }
        
        /// <summary>
        /// Raises the IdChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the IdChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnIdChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.IdChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveStatusAttribute()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("status")));
        }
        
        /// <summary>
        /// Raises the StatusChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStatusChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.StatusChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the StatusChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnStatusChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.StatusChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveWarenkorbReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("warenkorb")));
        }
        
        /// <summary>
        /// Raises the WarenkorbChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWarenkorbChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.WarenkorbChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the WarenkorbChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnWarenkorbChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.WarenkorbChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Warenkorb property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetWarenkorb(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Warenkorb))
            {
                this.Warenkorb = null;
            }
        }
        
        private static ITypedElement RetrieveVorstellungReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("vorstellung")));
        }
        
        /// <summary>
        /// Raises the VorstellungChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnVorstellungChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.VorstellungChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the VorstellungChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnVorstellungChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.VorstellungChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Vorstellung property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetVorstellung(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Vorstellung))
            {
                this.Vorstellung = null;
            }
        }
        
        private static ITypedElement RetrieveSitzplatzReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("sitzplatz")));
        }
        
        /// <summary>
        /// Raises the SitzplatzChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSitzplatzChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.SitzplatzChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the SitzplatzChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSitzplatzChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.SitzplatzChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Sitzplatz property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetSitzplatz(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Sitzplatz))
            {
                this.Sitzplatz = null;
            }
        }
        
        private static ITypedElement RetrieveKundeReference()
        {
            return ((ITypedElement)(((ModelElement)(KinoAppCore.Entities.Ticket.ClassInstance)).Resolve("kunde")));
        }
        
        /// <summary>
        /// Raises the KundeChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnKundeChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.KundeChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the KundeChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnKundeChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.KundeChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Kunde property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetKunde(object sender, EventArgs eventArgs)
        {
            if ((sender == this.Kunde))
            {
                this.Kunde = null;
            }
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "WARENKORB"))
            {
                return this.Warenkorb;
            }
            if ((reference == "VORSTELLUNG"))
            {
                return this.Vorstellung;
            }
            if ((reference == "SITZPLATZ"))
            {
                return this.Sitzplatz;
            }
            if ((reference == "KUNDE"))
            {
                return this.Kunde;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "ID"))
            {
                return this.Id;
            }
            if ((attribute == "STATUS"))
            {
                return this.Status;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "WARENKORB"))
            {
                this.Warenkorb = ((IWarenkorb)(value));
                return;
            }
            if ((feature == "VORSTELLUNG"))
            {
                this.Vorstellung = ((IVorstellung)(value));
                return;
            }
            if ((feature == "SITZPLATZ"))
            {
                this.Sitzplatz = ((ISitzplatz)(value));
                return;
            }
            if ((feature == "KUNDE"))
            {
                this.Kunde = ((IKunde)(value));
                return;
            }
            if ((feature == "ID"))
            {
                this.Id = ((int)(value));
                return;
            }
            if ((feature == "STATUS"))
            {
                this.Status = ((Ticketstatus)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "ID"))
            {
                return Observable.Box(new IdProxy(this));
            }
            if ((attribute == "STATUS"))
            {
                return Observable.Box(new StatusProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "WARENKORB"))
            {
                return new WarenkorbProxy(this);
            }
            if ((reference == "VORSTELLUNG"))
            {
                return new VorstellungProxy(this);
            }
            if ((reference == "SITZPLATZ"))
            {
                return new SitzplatzProxy(this);
            }
            if ((reference == "KUNDE"))
            {
                return new KundeProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Ticket")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Ticket class
        /// </summary>
        public class TicketReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Ticket _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public TicketReferencedElementsCollection(Ticket parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Warenkorb != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.Vorstellung != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.Sitzplatz != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.Kunde != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.WarenkorbChanged += this.PropagateValueChanges;
                this._parent.VorstellungChanged += this.PropagateValueChanges;
                this._parent.SitzplatzChanged += this.PropagateValueChanges;
                this._parent.KundeChanged += this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.WarenkorbChanged -= this.PropagateValueChanges;
                this._parent.VorstellungChanged -= this.PropagateValueChanges;
                this._parent.SitzplatzChanged -= this.PropagateValueChanges;
                this._parent.KundeChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Warenkorb == null))
                {
                    IWarenkorb warenkorbCasted = item.As<IWarenkorb>();
                    if ((warenkorbCasted != null))
                    {
                        this._parent.Warenkorb = warenkorbCasted;
                        return;
                    }
                }
                if ((this._parent.Vorstellung == null))
                {
                    IVorstellung vorstellungCasted = item.As<IVorstellung>();
                    if ((vorstellungCasted != null))
                    {
                        this._parent.Vorstellung = vorstellungCasted;
                        return;
                    }
                }
                if ((this._parent.Sitzplatz == null))
                {
                    ISitzplatz sitzplatzCasted = item.As<ISitzplatz>();
                    if ((sitzplatzCasted != null))
                    {
                        this._parent.Sitzplatz = sitzplatzCasted;
                        return;
                    }
                }
                if ((this._parent.Kunde == null))
                {
                    IKunde kundeCasted = item.As<IKunde>();
                    if ((kundeCasted != null))
                    {
                        this._parent.Kunde = kundeCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Warenkorb = null;
                this._parent.Vorstellung = null;
                this._parent.Sitzplatz = null;
                this._parent.Kunde = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Warenkorb))
                {
                    return true;
                }
                if ((item == this._parent.Vorstellung))
                {
                    return true;
                }
                if ((item == this._parent.Sitzplatz))
                {
                    return true;
                }
                if ((item == this._parent.Kunde))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Warenkorb != null))
                {
                    array[arrayIndex] = this._parent.Warenkorb;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.Vorstellung != null))
                {
                    array[arrayIndex] = this._parent.Vorstellung;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.Sitzplatz != null))
                {
                    array[arrayIndex] = this._parent.Sitzplatz;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.Kunde != null))
                {
                    array[arrayIndex] = this._parent.Kunde;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Warenkorb == item))
                {
                    this._parent.Warenkorb = null;
                    return true;
                }
                if ((this._parent.Vorstellung == item))
                {
                    this._parent.Vorstellung = null;
                    return true;
                }
                if ((this._parent.Sitzplatz == item))
                {
                    this._parent.Sitzplatz = null;
                    return true;
                }
                if ((this._parent.Kunde == item))
                {
                    this._parent.Kunde = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Warenkorb).Concat(this._parent.Vorstellung).Concat(this._parent.Sitzplatz).Concat(this._parent.Kunde).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the id property
        /// </summary>
        private sealed class IdProxy : ModelPropertyChange<ITicket, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public IdProxy(ITicket modelElement) : 
                    base(modelElement, "id")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Id;
                }
                set
                {
                    this.ModelElement.Id = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the status property
        /// </summary>
        private sealed class StatusProxy : ModelPropertyChange<ITicket, Nullable<Ticketstatus>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public StatusProxy(ITicket modelElement) : 
                    base(modelElement, "status")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<Ticketstatus> Value
            {
                get
                {
                    return this.ModelElement.Status;
                }
                set
                {
                    this.ModelElement.Status = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the warenkorb property
        /// </summary>
        private sealed class WarenkorbProxy : ModelPropertyChange<ITicket, IWarenkorb>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public WarenkorbProxy(ITicket modelElement) : 
                    base(modelElement, "warenkorb")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IWarenkorb Value
            {
                get
                {
                    return this.ModelElement.Warenkorb;
                }
                set
                {
                    this.ModelElement.Warenkorb = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the vorstellung property
        /// </summary>
        private sealed class VorstellungProxy : ModelPropertyChange<ITicket, IVorstellung>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public VorstellungProxy(ITicket modelElement) : 
                    base(modelElement, "vorstellung")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IVorstellung Value
            {
                get
                {
                    return this.ModelElement.Vorstellung;
                }
                set
                {
                    this.ModelElement.Vorstellung = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the sitzplatz property
        /// </summary>
        private sealed class SitzplatzProxy : ModelPropertyChange<ITicket, ISitzplatz>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public SitzplatzProxy(ITicket modelElement) : 
                    base(modelElement, "sitzplatz")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override ISitzplatz Value
            {
                get
                {
                    return this.ModelElement.Sitzplatz;
                }
                set
                {
                    this.ModelElement.Sitzplatz = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the kunde property
        /// </summary>
        private sealed class KundeProxy : ModelPropertyChange<ITicket, IKunde>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public KundeProxy(ITicket modelElement) : 
                    base(modelElement, "kunde")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IKunde Value
            {
                get
                {
                    return this.ModelElement.Kunde;
                }
                set
                {
                    this.ModelElement.Kunde = value;
                }
            }
        }
    }
}
