//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace SeeSharper.Models.Kino
{
    
    
    /// <summary>
    /// The default implementation of the Warenkorb class
    /// </summary>
    [XmlNamespaceAttribute("http://www.example.org/kino")]
    [XmlNamespacePrefixAttribute("kino")]
    [ModelRepresentationClassAttribute("http://www.example.org/kino#//Warenkorb")]
    public partial class Warenkorb : ModelElement, IWarenkorb, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Gesamtpreis property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<int> _gesamtpreis;
        
        private static Lazy<ITypedElement> _gesamtpreisAttribute = new Lazy<ITypedElement>(RetrieveGesamtpreisAttribute);
        
        /// <summary>
        /// The backing field for the Zahlungsmittel property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private Nullable<Zahlungsmittel> _zahlungsmittel;
        
        private static Lazy<ITypedElement> _zahlungsmittelAttribute = new Lazy<ITypedElement>(RetrieveZahlungsmittelAttribute);
        
        private static Lazy<ITypedElement> _ticketReference = new Lazy<ITypedElement>(RetrieveTicketReference);
        
        /// <summary>
        /// The backing field for the Ticket property
        /// </summary>
        [DebuggerBrowsableAttribute(DebuggerBrowsableState.Never)]
        private WarenkorbTicketCollection _ticket;
        
        private static IClass _classInstance;
        
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public Warenkorb()
        {
            this._ticket = new WarenkorbTicketCollection(this);
            this._ticket.CollectionChanging += this.TicketCollectionChanging;
            this._ticket.CollectionChanged += this.TicketCollectionChanged;
        }
        
        /// <summary>
        /// The gesamtpreis property
        /// </summary>
        [DisplayNameAttribute("gesamtpreis")]
        [CategoryAttribute("Warenkorb")]
        [XmlElementNameAttribute("gesamtpreis")]
        [XmlAttributeAttribute(true)]
        public Nullable<int> Gesamtpreis
        {
            get
            {
                return this._gesamtpreis;
            }
            set
            {
                if ((this._gesamtpreis != value))
                {
                    Nullable<int> old = this._gesamtpreis;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnGesamtpreisChanging(e);
                    this.OnPropertyChanging("Gesamtpreis", e, _gesamtpreisAttribute);
                    this._gesamtpreis = value;
                    this.OnGesamtpreisChanged(e);
                    this.OnPropertyChanged("Gesamtpreis", e, _gesamtpreisAttribute);
                }
            }
        }
        
        /// <summary>
        /// The Zahlungsmittel property
        /// </summary>
        [CategoryAttribute("Warenkorb")]
        [XmlAttributeAttribute(true)]
        public Nullable<Zahlungsmittel> Zahlungsmittel
        {
            get
            {
                return this._zahlungsmittel;
            }
            set
            {
                if ((this._zahlungsmittel != value))
                {
                    Nullable<Zahlungsmittel> old = this._zahlungsmittel;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnZahlungsmittelChanging(e);
                    this.OnPropertyChanging("Zahlungsmittel", e, _zahlungsmittelAttribute);
                    this._zahlungsmittel = value;
                    this.OnZahlungsmittelChanged(e);
                    this.OnPropertyChanged("Zahlungsmittel", e, _zahlungsmittelAttribute);
                }
            }
        }
        
        /// <summary>
        /// The ticket property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("ticket")]
        [CategoryAttribute("Warenkorb")]
        [XmlElementNameAttribute("ticket")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("warenkorb")]
        [ConstantAttribute()]
        public IOrderedSetExpression<ITicket> Ticket
        {
            get
            {
                return this._ticket;
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new WarenkorbReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Warenkorb")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired when the Gesamtpreis property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GesamtpreisChanged;
        
        /// <summary>
        /// Gets fired before the Gesamtpreis property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> GesamtpreisChanging;
        
        /// <summary>
        /// Gets fired when the Zahlungsmittel property changed its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> ZahlungsmittelChanged;
        
        /// <summary>
        /// Gets fired before the Zahlungsmittel property changes its value
        /// </summary>
        public event EventHandler<ValueChangedEventArgs> ZahlungsmittelChanging;
        
        private static ITypedElement RetrieveGesamtpreisAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Warenkorb.ClassInstance)).Resolve("gesamtpreis")));
        }
        
        /// <summary>
        /// Raises the GesamtpreisChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGesamtpreisChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GesamtpreisChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the GesamtpreisChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnGesamtpreisChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.GesamtpreisChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveZahlungsmittelAttribute()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Warenkorb.ClassInstance)).Resolve("Zahlungsmittel")));
        }
        
        /// <summary>
        /// Raises the ZahlungsmittelChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnZahlungsmittelChanged(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.ZahlungsmittelChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ZahlungsmittelChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnZahlungsmittelChanging(ValueChangedEventArgs eventArgs)
        {
            EventHandler<ValueChangedEventArgs> handler = this.ZahlungsmittelChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveTicketReference()
        {
            return ((ITypedElement)(((ModelElement)(SeeSharper.Models.Kino.Warenkorb.ClassInstance)).Resolve("ticket")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Ticket property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TicketCollectionChanging(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanging("Ticket", e, _ticketReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Ticket property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void TicketCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Ticket", e, _ticketReference);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "TICKET"))
            {
                if ((index < this.Ticket.Count))
                {
                    return this.Ticket[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "GESAMTPREIS"))
            {
                return this.Gesamtpreis;
            }
            if ((attribute == "ZAHLUNGSMITTEL"))
            {
                return this.Zahlungsmittel;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "TICKET"))
            {
                return this._ticket;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "GESAMTPREIS"))
            {
                this.Gesamtpreis = ((int)(value));
                return;
            }
            if ((feature == "ZAHLUNGSMITTEL"))
            {
                this.Zahlungsmittel = ((Zahlungsmittel)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "GESAMTPREIS"))
            {
                return Observable.Box(new GesamtpreisProxy(this));
            }
            if ((attribute == "ZAHLUNGSMITTEL"))
            {
                return Observable.Box(new ZahlungsmittelProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.example.org/kino#//Warenkorb")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Warenkorb class
        /// </summary>
        public class WarenkorbReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Warenkorb _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public WarenkorbReferencedElementsCollection(Warenkorb parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Ticket.Count);
                    return count;
                }
            }
            
            /// <summary>
            /// Registers event hooks to keep the collection up to date
            /// </summary>
            protected override void AttachCore()
            {
                this._parent.Ticket.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Unregisters all event hooks registered by AttachCore
            /// </summary>
            protected override void DetachCore()
            {
                this._parent.Ticket.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                ITicket ticketCasted = item.As<ITicket>();
                if ((ticketCasted != null))
                {
                    this._parent.Ticket.Add(ticketCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Ticket.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Ticket.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> ticketEnumerator = this._parent.Ticket.GetEnumerator();
                try
                {
                    for (
                    ; ticketEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = ticketEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    ticketEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                ITicket ticketItem = item.As<ITicket>();
                if (((ticketItem != null) 
                            && this._parent.Ticket.Remove(ticketItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Ticket).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the gesamtpreis property
        /// </summary>
        private sealed class GesamtpreisProxy : ModelPropertyChange<IWarenkorb, Nullable<int>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public GesamtpreisProxy(IWarenkorb modelElement) : 
                    base(modelElement, "gesamtpreis")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<int> Value
            {
                get
                {
                    return this.ModelElement.Gesamtpreis;
                }
                set
                {
                    this.ModelElement.Gesamtpreis = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Zahlungsmittel property
        /// </summary>
        private sealed class ZahlungsmittelProxy : ModelPropertyChange<IWarenkorb, Nullable<Zahlungsmittel>>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ZahlungsmittelProxy(IWarenkorb modelElement) : 
                    base(modelElement, "Zahlungsmittel")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Nullable<Zahlungsmittel> Value
            {
                get
                {
                    return this.ModelElement.Zahlungsmittel;
                }
                set
                {
                    this.ModelElement.Zahlungsmittel = value;
                }
            }
        }
    }
}
